### ISSUE TITLE
Language Checklist

### ISSUE THREAD

**Issue by kimlisa** [gravitational/webapps#312]
#### Description
Go through each screen and check/fix language (wording) with our editor

**applications**
- [x] empty state
- [x] empty read only
- [x] add app auto tab
- [x] add app auto created state
- [x] add app manually tab

**audit**
-  [x] overflow statement

**auth connectors**
- [x] enterprise empty state 
- [x] enterprise right side panel description
- [x] OS empty state 
- [x] OS right side panel description
- [x] delete dialogue

**invites**
- [x] invite
- [x] expired text
- [x] 2fa right side panel text

**login**
- [x] success state
- [x] failed texts

**nodes/servers**
- [x] add server auto tab
- [x] add server manual tab

**player**
- [x] unavailable texts

**roles**
- [x] role screen right side panel description
- [x] create/edit role dialogue (right side panel for setup instructions)
- [x] delete dialogue

**help and support**
- [ ] screen?

**trusted clusters**
- [x] empty state
- [x] right side panel (same texts as empty state though)
- [x] delete dialgoue

**users**
- [x] reset user password dialogue
- [x] reset user password share link dialogue
- [x] delete dialogue
- [x] create user share link dialogue

**billing**
- [x] screen for each tab?

**license warning**
html is from backend
~~- [ ] unable to process~~
~~- [ ] invalid license~~

**waiting room**
- [x] error
- [x] pending 
- [x] denied
- [x] reason input

**workflow**
- [x] screens?

**form invite**
- [x] u2f text
- [x] otp text
- [x] sso provider text
- [x] u2f press button text
- [x] disabled text

----------------------------------------
**kubernetes**
- [x] connect dialogue

**databases**
- [x]  add db manual instructions
- [x] connect dialogue
